## YAML Template.
---
MAX_TEMP: null

#When to turn the lights on after germination period
LIGHTS_ON_DATE: null

#What time of day to turn the lights on 
LIGHTS_ON_TIMEOFDAY: null
#What time of day to turn the lights off
LIGHTS_OFF_TIMEOFDAY: null

#How long to water the plants during a watering session
WATERING_TIME_LENGTH: null

#Array of time values for when water the plants
WATERING_SCHEDULE: null

#Array of time values for when to take a picture of the plants
PHOTO_SCHEDULE: null
